New metaldust properties
SWIFTSIM/velociraptor-python pull request #84
Opened 2022-05-19 13:59 UTC by james-trayford

See also https://github.com/SWIFTSIM/pipeline-configs/pull/180, enabling new multi-size grain dust properties and extra particle properties to be read in.

2022-05-25 07:41 UTC, bwvdnbro requested changes
I'm happy with the changes in `registration.py`, but I don't understand the changes in the other files. Are they necessary? If so, could you please add some comments explaining why these changes/additions have been made?

2022-05-25 07:41 UTC, bwvdnbro commented on velociraptor/autoplotter/compare.py
> +                inc = 0
What exactly is the point of this bit of code? Is this a leftover from debugging?

2022-05-25 07:41 UTC, bwvdnbro commented on velociraptor/autoplotter/objects.py
> +            except (UnitConversionError, ConversionError) as e:
Is there any particular reason why a `ConversionError` would be thrown by the new data?

2022-06-02 15:20 UTC, james-trayford commented
@bwvdnbro you're right these other file changes are obsolete, updated

2022-06-03 13:53 UTC, bwvdnbro approved these changes

2022-06-03 13:59 UTC, bwvdnbro commented
Could you apply the (brand new) formatting script before I merge this?

2022-06-03 14:59 UTC, james-trayford commented
@bwvdnbro thanks, hope that's all good

2022-06-03 15:07 UTC, merged